### PR TITLE
Use a single tuple expression instead of pairs and units

### PR DESCRIPTION
**Pull request by brendanzab**
Not sure if this is helpful at all! Just thought it might simplify some things.

### CODE REVIEW

**Comment by mikeday** [comment]
I'm thinking we might actually want to distinguish tuple values and sequence values :thinking:

**Comment by brendanzab** [comment]
Yeah, this does that!

**Comment by mikeday** [comment]
Oh sorry, I misread! Let me look a little more carefully :nerd_face:

**Review by mikeday — APPROVED** [review]
That looks good to me!

**Comment by brendanzab** [comment]
Feel free to wait till merging the #16 as I assume there’ll be some conflicts.

**Pull request merged**
