### PR TITLE
Do a better job of recovering mapped formats

### PR DESCRIPTION
**Pull request by brendanzab**
This handles the possibility of multiple projections in map formats

### CODE REVIEW

**Comment by mikeday** [comment]
I'm curious what effect this has on the output, currently mapped formats confuse me a little

**Comment by mikeday** [comment]
Oops hit close on the pull request :facepalm:

**Comment by brendanzab** [comment]
It doesn’t have any effect on the current mapped output as we don’t have any cases of formats like `map (fun x => x.foo.bar.3) format` yet. Currently we only handle `map (fun x => x.foo) format` and `map (fun x => x.1) format`.

**Comment by brendanzab** [comment]
Updated the `mapped_format` function with a doc comment that hopefully clarifies things more

**Review by mikeday — APPROVED** [review]
Looks good!

**Pull request merged**
